image:
  repository: galaxy/galaxy-min
  tag: latest
  # pullPolicy: Always
cvmfs:
  enabled: true
  deploy: false
  cache:
    alienCache:
      storageClass: nfs
persistence:
  storageClass: nfs
  size: 1Gi
configs:
  job_conf.yml:
    execution:
      environments:
        dynamic_k8s_dispatcher:
          container_monitor: false
    runners:
      k8s:
        k8s_run_as_user_id: '0'
        k8s_run_as_group_id: '0'
        k8s_interactivetools_use_ssl: true
        k8s_interactivetools_ingress_annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          kubernetes.io/tls-acme: "true"
  galaxy.yml:
    galaxy:
      logo_src: /examplepath/static/favicon.png
      interactivetools_enable: true
      outputs_to_working_directory: true
      interactivetools_prefix: it
      interactivetools_map: database/interactivetools_map.sqlite
      interactivetools_proxy_host: "{{ $host := index .Values.ingress.hosts 0 }}{{$host.host}}"
      interactivetools_base_path: "{{$host := index .Values.ingress.hosts 0}}{{$path := index $host.paths 0}}{{$path.path}}"
      interactivetools_shorten_url: True
      tool_config_file: "/galaxy/server/config/tool_conf.xml,/cvmfs/cloud.galaxyproject.org/config/shed_tool_conf.xml,/galaxy/server/config/tool_conf_its.xml"
  tool_conf_its.xml: |
    <toolbox monitor="true">
        <section id="interactivetools" name="Interactive Tools">
            <tool file="interactive/interactivetool_jupyter_notebook.xml" />
            <tool file="interactive/interactivetool_terminal.xml" />
            <tool file="interactive/interactivetool_askomics.xml" />
            <tool file="interactive/interactivetool_bam_iobio.xml" />
            <tool file="interactive/interactivetool_cellxgene.xml" />
            <tool file="interactive/interactivetool_climate_notebook.xml" />
            <tool file="interactive/interactivetool_ethercalc.xml" />
            <tool file="interactive/interactivetool_geoexplorer.xml" />
            <tool file="interactive/interactivetool_guacamole_desktop.xml" />
            <tool file="interactive/interactivetool_hicbrowser.xml" />
            <tool file="interactive/interactivetool_higlass.xml" />
            <tool file="interactive/interactivetool_openrefine.xml" />
            <tool file="interactive/interactivetool_panoply.xml" />
            <tool file="interactive/interactivetool_paraview.xml" />
            <tool file="interactive/interactivetool_phinch.xml" />
            <tool file="interactive/interactivetool_pyiron.xml" />
            <tool file="interactive/interactivetool_radiant.xml" />
            <tool file="interactive/interactivetool_rstudio.xml" />
            <tool file="interactive/interactivetool_vcf_iobio.xml" />
            <tool file="interactive/interactivetool_wallace.xml" />
            <tool file="interactive/interactivetool_wilson.xml" />
            <tool file="/galaxy/server/config/interactivetool_terminal.xml" />
        </section>
    </toolbox>
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: "domain.example.com"
      paths:
        - path: "/examplepath"
  path: "/examplepath"
  tls:
    - hosts: ["domain.example.com"]
      secretName: "galaxy-domain-example-com-key"
postgresql:
  galaxyDatabasePassword: qweasdzxc

